Middleware added to redirect the user if the trial site expires
edly-io/ecommerce pull request #115
Opened 2022-11-15 11:02 UTC by marslanabdulrauf

** Description: **
This PR adds a middle to redirect user to pricing page if the trial site expires

**JIRA:** 
https://edlyio.atlassian.net/browse/EDLY-4882

2022-11-15 12:21 UTC, taimoor-ahmed-1 requested changes

2022-11-15 12:21 UTC, taimoor-ahmed-1 commented on ecommerce/extensions/edly_ecommerce_app/middleware.py
> +            logger.warning('Site (%s) has no related site configuration.', current_site)
kindly remove the log output as it bloats the logs for sample sites.

2022-11-15 12:21 UTC, taimoor-ahmed-1 commented on ecommerce/extensions/edly_ecommerce_app/middleware.py
> +            if django_override_settings.get('CURRENT_PLAN') == 'trial expired' and not _is_logged_in_path(request.path):
we should add `trial expired` in constants and use the constant here.

2022-11-15 18:43 UTC, taimoor-ahmed-1 approved these changes
LGTM

2022-11-18 06:18 UTC, madnihamza1841 approved these changes
LGTM

2022-11-18 07:26 UTC, merged