API to cover self service usecases
edly-io/ecommerce pull request #124
Opened 2023-02-15 13:13 UTC by madnihamza1841

**Description:**
Updating the Self Service API to handle Site Config and Site Theme updates.

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-3551

2023-02-16 13:15 UTC, muhammadali124 approved these changes

2023-02-20 06:29 UTC, taimoor-ahmed-1 requested changes

2023-02-20 06:29 UTC, taimoor-ahmed-1 commented on ecommerce/extensions/edly_ecommerce_app/api/v1/views.py
> +                site_configurations[field] = self._update_django_settings_override_for_site(site_configurations.get('DJANGO_SETTINGS_OVERRIDE', {}), request_data.get('DJANGO_SETTINGS_OVERRIDE', {}))
kindly format this line properly

2023-02-20 07:05 UTC, taimoor-ahmed-1 commented on ecommerce/extensions/edly_ecommerce_app/api/v1/views.py
> +                site_configurations[field] = self._update_django_settings_override_for_site(site_configurations.get('DJANGO_SETTINGS_OVERRIDE', {}), request_data.get('DJANGO_SETTINGS_OVERRIDE', {}))
```
site_configurations[field] = self._update_django_settings_override_for_site(
    site_configurations.get('DJANGO_SETTINGS_OVERRIDE', {}), 
    request_data.get('DJANGO_SETTINGS_OVERRIDE', {}),
)

```

2023-02-20 07:08 UTC, taimoor-ahmed-1 approved these changes

2023-02-20 07:09 UTC, merged