Fixed sorting for actual price and price columns in subscriptions tab
edly-io/ecommerce pull request #146
Opened 2024-10-23 12:55 UTC by manan-memon

# ⛔️ MAIN BRANCH WARNING! 2U EMPLOYEES must make branches against the 2u/main BRANCH

- [ ] I have checked the branch to which I would like to merge.

# ⛔️ DEPRECATION WARNING

**This repository is deprecated and in maintainence-only operation while we work on a replacement, please see [this announcement](https://discuss.openedx.org/t/deprecation-removal-ecommerce-service-depr-22/6839) for more information.**

Although we have stopped integrating new contributions, we always appreciate security disclosures and patches sent to [security@edx.org](mailto:security@edx.org)

## Anyone internally merging to this repository is expected to [release and monitor their changes](https://openedx.atlassian.net/wiki/spaces/RS/pages/1835106870/How+to+contribute+to+our+repositories); if you are not able to do this DO NOT MERGE, please coordinate with someone who can to ensure that the changes are released.

## Required Testing
- [ ] Before deploying this change, complete a purchase in the stage environment. 
(^ We can remove that manual check once REV-2624 is done and the corresponding e2e test runs again)

## Description

Describe what this pull request changes, and why these changes were made. How will these changes affect other people, installations of edx, etc.?
Please include links to any relevant ADRs, design artifacts, and decision documents. Make sure to document the rationale behind significant changes in the repo, per [OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.

Useful information to include:
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author", "Developer", and "Operator".
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these changes.

## Supporting information

Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.

## Testing instructions

Please provide detailed step-by-step instructions for testing this change; how did YOU test this change?

## Other information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, OpenEdx vs. edx.org differences, development vs. production environment differences, security, or accessibility.

2024-10-23 15:06 UTC, Anas-hameed approved these changes

2024-10-24 09:12 UTC, muhammadali286 requested changes

2024-10-24 09:12 UTC, muhammadali286 commented on ecommerce/static/js/views/subscription_list_view.js
> +            }
nit: Simple arrow function will work
```
"currency-asc": (a, b) => a - b,
"currency-desc": (a, b) => b - a
```

2024-10-24 09:12 UTC, muhammadali286 commented on ecommerce/static/js/views/subscription_list_view.js
> +                return parseFloat(value.replace(/[^\d.-]/g, '')) || 0;
What if extracted value is not a number? 

```
const numericValue = parseFloat(value.replace(/[^\d.-]/g, ''));
return isNaN(numericValue) ? 0 : numericValue;
```

2024-10-24 09:29 UTC, manan-memon commented on ecommerce/static/js/views/subscription_list_view.js
> +                return parseFloat(value.replace(/[^\d.-]/g, '')) || 0;
`parseFloat` will either have a number or an empty string as the regex expression in `value.replace(`) replaces all non-numeric values. Even if it gets a NaN the `|| 0` part will fall back to 0, sorting it accordingly.

2024-10-24 09:38 UTC, manan-memon commented on ecommerce/static/js/views/subscription_list_view.js
> +            }
I just rechecked and found out that we have not used arrow function anywhere in the project. Should I keep it consistent with the repo's standard or replace it with arrow functions?

2024-10-24 09:47 UTC, muhammadali286 approved these changes

2024-10-24 09:49 UTC, merged