Adds partner sku in response data and a subscription active filter
edly-io/ecommerce pull request #41
Opened 2020-08-31 08:29 UTC by rehan99000

**Description:**
This PR adds the following:
- Partner sku for each subscription to help create a basket link
- A query param filter `filter_active` with values `true/false` to get only active subscriptions

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-1835

2020-08-31 08:37 UTC, iam-mhaseeb commented on ecommerce/subscriptions/api/v2/serializers.py
> +        return product.stockrecords.first().partner_sku
Can product have multiple stockrecords? If yes, will there partner_sku would be the same?

2020-08-31 08:57 UTC, asadmanzoor93 requested changes
Kindly update unit tests for the change.

2020-08-31 09:01 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +        return product.stockrecords.first().partner_sku
Nope.there will be a single stock record against each subscription

2020-09-01 07:59 UTC, zubair-arbi approved these changes
LGTM 👍

2020-09-01 08:46 UTC, ziafazal approved these changes
👍

2020-09-01 09:23 UTC, iam-mhaseeb approved these changes
If it's not urgent, adding tests suggested.

2020-09-01 09:34 UTC, asadmanzoor93 approved these changes

2020-09-01 09:36 UTC, merged