added flag in site configuration for individual course payments, impl…
edly-io/ecommerce pull request #43
Opened 2020-09-10 10:42 UTC by rehan99000

This PR adds the following:
- Fulfillment module for publishing user subscription to LMS
- Course individual payments implementation (ecommerce side) (frontend and backend)
- Bug fixes and cleanup

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-1818

2020-09-10 11:19 UTC, rehan99000 commented on ecommerce/extensions/api/serializers.py
> +        value = obj.value.option if obj.attribute.type == 'option' else obj.value
required for option attributes of subscription for order history view in LMS

2020-09-10 12:38 UTC, ziafazal requested changes
@rehan99000 overall looks good few minor things to look into.

2020-09-11 05:42 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/views.py
> +    @list_route(methods=['get'])
@ziafazal The `POST` call requires a csrf token that for some reason is not sent when I call it from the backbone. Should I use `POST` with csrf exempt?

2020-09-11 05:44 UTC, rehan99000 commented on ecommerce/static/js/views/confirmation_dialog_view.js
> +            var course_individual_payments_button = $('[name=course-individual-payments]');
It was showing fine with me. still auto formatted

2020-09-14 07:01 UTC, ziafazal commented on ecommerce/static/js/views/confirmation_dialog_view.js
> +				context: this,
@rehan99000 
You pass CSRF token like this
```
  headers: {
                        'X-CSRFToken': Cookies.get('ecommerce_csrftoken')
                    },
```

2020-09-17 12:33 UTC, rehan99000 commented on ecommerce/static/js/views/confirmation_dialog_view.js
> +				context: this,
done

2020-09-22 07:03 UTC, zubair-arbi requested changes
I have added my feedback.

2020-09-22 07:03 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def get_course_individual_payments(self, product):
`get_course_payments_enabled`

2020-09-22 07:03 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +            'subscription_status', 'display_order', 'partner_sku', 'course_individual_payments'
`course_payments_enabled`

2020-09-22 07:03 UTC, zubair-arbi commented on ecommerce/subscriptions/modules.py
> +        logger.info("Finished fulfilling 'Subscription' product types for order [%s]", order.number)
nit: add a new line before de-indent

2020-09-24 10:25 UTC, rehan99000 commented on ecommerce/settings/_oscar.py
> +    'ecommerce.subscriptions.modules.SubscriptionFulfillmentModule',
done

2020-09-24 10:25 UTC, rehan99000 commented on ecommerce/core/models.py
> +        help_text=_('Flag to check if site wise course individual payments are enabled'),
done

2020-09-24 10:25 UTC, rehan99000 commented on ecommerce/settings/_oscar.py
> +USER_SUBSCRIPTION_FULFILLMENT_TIMEOUT = 7
done

2020-09-24 10:26 UTC, rehan99000 commented on ecommerce/core/models.py
> +    enable_course_individual_payments = models.BooleanField(
done

2020-09-24 10:29 UTC, rehan99000 commented on ecommerce/static/js/views/subscription_list_view.js
> +            toggleIndividualCoursePaymentsButtonText: function() {
done

2020-09-24 10:29 UTC, rehan99000 commented on ecommerce/static/templates/individual_payments_action_modal.html
> +<div class="modal fade" id="individualPaymentsActionModal" tabindex="-1" role="dialog"
done

2020-09-24 10:29 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def get_course_individual_payments(self, product):
done

2020-09-24 10:29 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +            'subscription_status', 'display_order', 'partner_sku', 'course_individual_payments'
done

2020-09-24 10:29 UTC, rehan99000 commented on ecommerce/subscriptions/modules.py
> +        logger.info("Finished fulfilling 'Subscription' product types for order [%s]", order.number)
done

2020-09-28 09:11 UTC, rehan99000 commented on ecommerce/extensions/api/serializers.py
> +        value = obj.value.option if obj.attribute.type == 'option' else obj.value
done

2020-09-28 09:11 UTC, rehan99000 commented on ecommerce/static/js/views/confirmation_dialog_view.js
> +            var course_individual_payments_button = $('[name=course-individual-payments]');
done

2020-09-28 12:59 UTC, zubair-arbi requested changes
I have added some more feedback.

2020-09-28 12:59 UTC, zubair-arbi commented on ecommerce/core/migrations/0050_add_course_individual_flag_in_siteconfiguration.py
> +# -*- coding: utf-8 -*-
Please delete this migration and create again as the name of this migration doesn't seem right `0050_add_course_individual_flag_in_siteconfiguration.py`

2020-09-28 12:59 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def get_course_payments(self, product):
rename it to `is_course_payments_enabled`

2020-09-28 12:59 UTC, zubair-arbi commented on ecommerce/subscriptions/modules.py
> +                    "Unable to fulfill line [%d] of order [%s] due to a request time out", line.id, order.number
Be consistent with using single quotes.

2020-09-28 12:59 UTC, zubair-arbi commented on ecommerce/static/js/views/confirmation_dialog_view.js
> +			var course_payments_button = $('[name=course-payments]');
Javascript recommends camel case for declaring variable names.
Rename it to `coursePaymentsButton`

2020-09-29 06:13 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def get_course_payments(self, product):
This is a serializer method field get method, it needs to have the `get_` prefix.

2020-09-29 06:15 UTC, rehan99000 commented on ecommerce/subscriptions/modules.py
> +                    "Unable to fulfill line [%d] of order [%s] due to a request time out", line.id, order.number
done

2020-09-29 06:15 UTC, rehan99000 commented on ecommerce/static/js/views/confirmation_dialog_view.js
> +			var course_payments_button = $('[name=course-payments]');
done

2020-09-29 06:16 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def get_course_payments(self, product):
to change this, I would have to mention it explicitly in the field declaration. Do u want me to do that?

2020-09-29 06:22 UTC, rehan99000 commented on ecommerce/core/migrations/0050_add_course_individual_flag_in_siteconfiguration.py
> +# -*- coding: utf-8 -*-
done

2020-09-29 11:33 UTC, ziafazal approved these changes
@rehan99000 Overall looks good. One question and one suggestion.

2020-09-29 11:33 UTC, ziafazal commented on ecommerce/static/templates/subscription_list.html
> +            <a href = '#' class="btn btn-primary btn-small" name="course-payments" data-toggle="modal"
@rehan99000 this href tag has formatting issues like spaces around equal operation and why we don't have display text in it?.

2020-09-29 11:33 UTC, ziafazal commented on ecommerce/subscriptions/modules.py
> +            logger.info('Attempting to revoke fulfillment of Line [%d]...', line.id)
which code revokes fulfillment of line?

2020-09-29 11:41 UTC, rehan99000 commented on ecommerce/subscriptions/modules.py
> +            logger.info('Attempting to revoke fulfillment of Line [%d]...', line.id)
@ziafazal https://github.com/edly-io/ecommerce/blob/a2ee36711311ad65a7a966dd3188296b6b8bf4ce/ecommerce/extensions/fulfillment/api.py#L57

2020-09-29 11:42 UTC, rehan99000 commented on ecommerce/static/templates/subscription_list.html
> +            <a href = '#' class="btn btn-primary btn-small" name="course-payments" data-toggle="modal"
display text on this is set through jquery as we need to display `Enable course payments`/`Disable course payments` according to the flag value in site configuration. format issue fixed.

2020-09-30 07:48 UTC, asadmanzoor93 reviewed
@rehan99000 is there a separate PR for unit tests covering this functionality?

2020-09-30 14:00 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def get_course_payments(self, product):
Lets change it to `get_is_course_payments_enabled` and in field declaration use `is_course_payments_enabled`

2020-09-30 14:13 UTC, zubair-arbi requested changes
Some small nits. Otherwise changes looks good.
Please add some tests for the subscriptions module

2020-09-30 14:13 UTC, zubair-arbi commented on ecommerce/extensions/api/serializers.py
> +        return value
nit: add a new line before code de-indent

2020-09-30 14:13 UTC, zubair-arbi commented on ecommerce/subscriptions/modules.py
> +        Args:
Always use full word `Arguments` (https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#docstrings)

2020-09-30 14:13 UTC, zubair-arbi commented on ecommerce/subscriptions/modules.py
> +            order (Order): The Order associated with the lines to be fulfilled. The user associated with the order
```
The Order associated with the lines to be fulfilled. The user associated with the order
is presumed to be the student buying the subscription.
```

2020-10-01 12:32 UTC, rehan99000 commented on ecommerce/subscriptions/modules.py
> +            order (Order): The Order associated with the lines to be fulfilled. The user associated with the order
done

2020-10-01 12:32 UTC, rehan99000 commented on ecommerce/subscriptions/modules.py
> +        Args:
done. it got left while copying from the other module

2020-10-01 12:33 UTC, rehan99000 commented on ecommerce/extensions/api/serializers.py
> +        return value
done

2020-10-01 12:33 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def get_course_payments(self, product):
done

2020-10-01 12:53 UTC, zubair-arbi approved these changes
Change looks good now 👍 
Good job.

2020-10-01 12:54 UTC, rehan99000 commented
> @rehan99000 is there a separate PR for unit tests covering this functionality?

Yes there will be a separate PR for all the tests

2020-10-02 05:01 UTC, merged