Subscriptions Part 3
edly-io/ecommerce pull request #47
Opened 2020-09-18 11:05 UTC by rehan99000

**Description:**
This PR adds the following:
- Adds conditional offer for subscriptions
- Adds subscription condition
- Applies valid user subscription if passed `subscription=true` in query parameters while adding a course seat to the basket
- Posts subscription information with enrollment fulfillment.

2020-09-22 08:16 UTC, zubair-arbi requested changes
I have added my feedback.

2020-09-22 08:16 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +        Create a conditional offer agains a subscription.
`Create a conditional offer against the provided subscription.`

2020-09-22 08:16 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +        offer_name = _(u'Subscription offer for the "{subscription_title}" subscription of type "{subscription_type}"'.format(
```python
offer_name = _(u'Subscription offer of type "{subscription_type}" for "{subscription_title}"'.format(
    subscription_type=subscription_type,
    subscription_title=subscription.title,
))
```

2020-09-22 08:16 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +        Expire the conditional offer if subscription is changed to Inactive.
`Set the conditional offer expired if status of its related subscription is changed to inactive.`

2020-09-22 08:16 UTC, zubair-arbi commented on ecommerce/subscriptions/benefits.py
> +    PercentageBenefitMixin
nit: add comma after last item as well to reduce git diff in future changes.

2020-09-22 08:16 UTC, zubair-arbi commented on ecommerce/subscriptions/benefits.py
> +    """ PercentageDiscountBenefit without an attached range.
```
""" 
"PercentageDiscountBenefit" without an attached range.

The range is only used for the name and description. We would prefer not
to deal with ranges since we rely on the condition to fully determine if
a conditional offer is applicable to a basket.
"""
```

2020-09-22 08:16 UTC, zubair-arbi commented on ecommerce/subscriptions/conditions.py
> +        Args:
Add proper docstrings https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#docstrings

2020-09-22 08:16 UTC, zubair-arbi commented on ecommerce/subscriptions/conditions.py
> +        for line in basket.all_lines():
Add new line before de-indent.

2020-09-22 08:16 UTC, zubair-arbi commented on ecommerce/subscriptions/custom.py
> +    Create a custom condition instance
Create a custom condition instance for subscription.

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/custom.py
> +    Create a custom condition instance
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/conditions.py
> +        for line in basket.all_lines():
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/conditions.py
> +        Args:
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/benefits.py
> +    """ PercentageDiscountBenefit without an attached range.
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/benefits.py
> +    PercentageBenefitMixin
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +        Expire the conditional offer if subscription is changed to Inactive.
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +        offer_name = _(u'Subscription offer for the "{subscription_title}" subscription of type "{subscription_type}"'.format(
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +        Create a conditional offer agains a subscription.
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/extensions/basket/utils.py
> +                'User [%s] attempted to purchase an inactive subscription or already has a purchased valid subscription',
done

2020-09-22 10:50 UTC, rehan99000 commented on ecommerce/subscriptions/exceptions.py
> +    Exception for user if he already has an active subscription or the subscription is inactive.
done

2020-09-28 13:16 UTC, zubair-arbi requested changes
Overall changes looks good, just small suggestions.

2020-09-28 13:16 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +       offer_name = _(u'Subscription offer of type "{subscription_type}" for "{subscription_title}"'.format(
nit: fix indentation

2020-09-28 13:16 UTC, zubair-arbi commented on ecommerce/subscriptions/utils.py
> +    return data_list
nit: add new line before de-indent.

2020-09-28 13:16 UTC, zubair-arbi commented on ecommerce/subscriptions/utils.py
> +    """
Add missing docstring.

2020-09-28 13:16 UTC, zubair-arbi commented on ecommerce/subscriptions/utils.py
> +    """
add missing docsrting

2020-09-28 13:16 UTC, zubair-arbi commented on ecommerce/subscriptions/utils.py
> +from edx_django_utils.cache import TieredCache
fix import order (use isort)

2020-09-29 07:22 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +       offer_name = _(u'Subscription offer of type "{subscription_type}" for "{subscription_title}"'.format(
done

2020-09-29 07:22 UTC, rehan99000 commented on ecommerce/subscriptions/utils.py
> +    return data_list
done

2020-09-29 07:23 UTC, rehan99000 commented on ecommerce/subscriptions/utils.py
> +    """
done

2020-09-29 07:23 UTC, rehan99000 commented on ecommerce/subscriptions/utils.py
> +    """
done

2020-09-29 07:23 UTC, rehan99000 commented on ecommerce/subscriptions/utils.py
> +from edx_django_utils.cache import TieredCache
done

2020-09-30 08:28 UTC, ziafazal requested changes
@rehan99000 completed my review.

2020-09-30 08:28 UTC, ziafazal commented on ecommerce/subscriptions/api/v2/serializers.py
> +        subscription_offer = ConditionalOffer(
We should use 
```
ConditionalOffer.objects.get_or_create(
 status=ConditionalOffer.OPEN,
            offer_type=ConditionalOffer.SITE,
            partner=partner
)
One partner should have one conditional offer for all of its subscriptions

2020-09-30 08:28 UTC, ziafazal commented on ecommerce/subscriptions/api/v2/serializers.py
> +                self._create_conditional_offer(subscription)
pass `partner` in the param to avoid being pulled in downstream.

2020-09-30 08:28 UTC, ziafazal commented on ecommerce/subscriptions/api/v2/serializers.py
> +        subscription_offer.condition, ___ = create_condition(SubscriptionCondition, subscription=subscription)
I don't think we need to link `subscription` with condition.
One generic subscription condition should work for all conditional offers and one generic benefit should work for all conditional offers.

2020-09-30 08:28 UTC, ziafazal commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def _update_conditional_offer(self, subscription):
this might not be needed.

2020-09-30 08:28 UTC, ziafazal commented on ecommerce/subscriptions/conditions.py
> +                attribute_type=BasketAttributeType.objects.get(name=SUBSCRIPTION_ATTRIBUTE_TYPE),
why we need this?
applicable lines are non discounted course seats.

2020-09-30 08:28 UTC, ziafazal commented on ecommerce/subscriptions/conditions.py
> +    def is_satisfied(self, offer, basket):  # pylint: disable=unused-argument
this is to check if buyer has already purchased a subscription and that subscription is for partner of current site and it is valid(not consumed and active).
This condition is not applied when a buy is buying subscription instead it is applied when a buyer is buying course using already purchased subscription.

2020-09-30 08:28 UTC, ziafazal commented on ecommerce/subscriptions/api/v2/serializers.py
> +        subscription_benefit, ___ = Benefit.objects.get_or_create(
nit: `create_benefit` method could be created as we have `create_condition`

2020-09-30 11:13 UTC, rehan99000 commented on ecommerce/subscriptions/conditions.py
> +                attribute_type=BasketAttributeType.objects.get(name=SUBSCRIPTION_ATTRIBUTE_TYPE),
This is to check if a course is being purchased through a subscription or individually. when we make a call to add a course seat to the basket, we can pass an additional query param `subscription` which sets a basket attribute to let the condition know if the subscription condition needs to be applied or not.

2020-09-30 11:15 UTC, rehan99000 commented on ecommerce/subscriptions/conditions.py
> +    def is_satisfied(self, offer, basket):  # pylint: disable=unused-argument
Yes, I know that. If you are referring to the `ENABLE_SUBSCRIPTIONS_ON_RUNTIME_SWITCH ` applicability, I just added it as an additional check so a user can't purchase a course through subscription even if one tries to while subscriptions are disabled.

2020-09-30 11:15 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +        subscription_benefit, ___ = Benefit.objects.get_or_create(
done

2020-09-30 11:18 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def _update_conditional_offer(self, subscription):
I added this as an additional check so if a subscription is made inactive, the condition gets expired too, since each subscription has a condition attached to it. But it is not critical to the functionality I think and can be removed

2020-09-30 11:24 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +        subscription_offer.condition, ___ = create_condition(SubscriptionCondition, subscription=subscription)
@ziafazal the benefit is already generic i.e. one benefit for all subscriptions. The main reason to link subscription with the condition was to retrieve a user's subscription while consuming it for a course as I couldn't find another way to retrieve the subscription from the offer being applied which is needed to add the enrollment to the user subscription in LMS.

2020-09-30 11:24 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +                self._create_conditional_offer(subscription)
done

2020-09-30 11:27 UTC, rehan99000 commented on ecommerce/subscriptions/utils.py
> +@newrelic.agent.function_trace()
This was added to the other functions which were setting basket attributes like https://github.com/edly-io/ecommerce/blob/a2ee36711311ad65a7a966dd3188296b6b8bf4ce/ecommerce/extensions/basket/utils.py#L297 or https://github.com/edly-io/ecommerce/blob/a2ee36711311ad65a7a966dd3188296b6b8bf4ce/ecommerce/extensions/basket/utils.py#L329 . This can be removed if this is unnecessary for us.

2020-09-30 11:39 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +        subscription_offer = ConditionalOffer(
refer to https://github.com/edly-io/ecommerce/pull/47#discussion_r497433797

2020-09-30 14:34 UTC, zubair-arbi requested changes
I have add more feedback.

2020-09-30 14:34 UTC, zubair-arbi commented on ecommerce/subscriptions/utils.py
> +def subscription_is_buyable(subscription, user, site):
Rename `is_subscription_buyable`

2020-09-30 14:34 UTC, zubair-arbi commented on ecommerce/subscriptions/conditions.py
> +            line_tuples.append((price, line))
nit: add a newline before code de-indent

2020-09-30 14:34 UTC, zubair-arbi commented on ecommerce/subscriptions/conditions.py
> +        Returns:
nit: Add a new line between docstring sections: https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#docstrings

2020-09-30 14:34 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def _update_conditional_offer(self, subscription):
I think we should remove it. Reason is that if a learner has already bought a subscription so that learner should be able to use his/her subscription to enroll in paid courses even if the cloud customer marks the subscription in ECOM as inactive.

2020-09-30 14:34 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/serializers.py
> +        subscription_offer.condition, ___ = create_condition(SubscriptionCondition, subscription=subscription)
Please check following benefits:
Enterprise benefits: https://github.com/edx/ecommerce/blob/master/ecommerce/enterprise/benefits.py
Programs benefits: https://github.com/edx/ecommerce/blob/master/ecommerce/programs/benefits.py

2020-10-01 05:44 UTC, ziafazal commented on ecommerce/subscriptions/utils.py
> +    subscription_attribute, __ = BasketAttributeType.objects.get_or_create(name=SUBSCRIPTION_ATTRIBUTE_TYPE)
move this down after if

2020-10-01 12:36 UTC, rehan99000 commented on ecommerce/subscriptions/utils.py
> +    subscription_attribute, __ = BasketAttributeType.objects.get_or_create(name=SUBSCRIPTION_ATTRIBUTE_TYPE)
done

2020-10-01 12:55 UTC, rehan99000 commented on ecommerce/subscriptions/utils.py
> +def subscription_is_buyable(subscription, user, site):
done

2020-10-01 12:55 UTC, rehan99000 commented on ecommerce/subscriptions/conditions.py
> +            line_tuples.append((price, line))
done

2020-10-01 12:55 UTC, rehan99000 commented on ecommerce/subscriptions/conditions.py
> +        Returns:
done

2020-10-01 13:01 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/serializers.py
> +    def _update_conditional_offer(self, subscription):
done

2020-10-01 13:12 UTC, zubair-arbi approved these changes
Changes look good now. Thanks for the hard work. 👍 🚢

2020-10-02 05:46 UTC, ziafazal approved these changes
@rehan99000 overall looks good just minor change suggested.

2020-10-02 05:46 UTC, ziafazal commented on ecommerce/subscriptions/conditions.py
> +        line_tuples = []
please rename this to `applicable_lines`

2020-10-02 05:46 UTC, ziafazal commented on ecommerce/subscriptions/custom.py
> +# TODO: Issue above is fixed; we need to upgrade to django-oscar==1.5 and this can be removed.
@rehan99000 we are using `django-oscar` version `1.5.4` which means we don't need to copy these functions?

2020-10-02 05:55 UTC, rehan99000 commented on ecommerce/subscriptions/custom.py
> +# TODO: Issue above is fixed; we need to upgrade to django-oscar==1.5 and this can be removed.
The models were previously being imported without django oscar's `get_model`, it has been fixed in a previous commit so we don't need to do anything

2020-10-02 06:00 UTC, iam-mhaseeb approved these changes
🥇

2020-10-02 06:09 UTC, rehan99000 commented on ecommerce/subscriptions/conditions.py
> +        line_tuples = []
done

2020-10-02 06:09 UTC, merged