Adds unit tests for ecommerce subscriptions flow
edly-io/ecommerce pull request #56
Opened 2020-10-23 10:52 UTC by rehan99000

**Description:**
Adds unit tests and factories for subscription flow on ecommerce.

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-2006

2020-10-26 08:36 UTC, zubair-arbi requested changes
Thank you for adding such detailed tests.
I have added some small suggestions.

2020-10-26 08:36 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +        'number_of_courses': FuzzyInteger(1, 10).fuzz(),
We have added `subscription` as a prefix in attributes names to distinguish them from other generic attributes. I think we need to also add this prefix for `number_of_courses` as well.
`subscription_number_of_courses`

2020-10-26 08:36 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +def MockUserSubscriptionFactory():
nit: expected two lines before this method

2020-10-26 08:36 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/tests/test_views.py
> +            'subscription_active_status': 'true',
@rehan99000 where are we using this attribute `subscription_active_status`?

2020-10-26 08:36 UTC, zubair-arbi commented on ecommerce/subscriptions/tests/test_modules.py
> +    Unit tests for "SubscriptionModule".
nit: `SubscriptionFulfillmentModule`

2020-10-26 08:36 UTC, zubair-arbi commented on ecommerce/subscriptions/tests/test_modules.py
> +        Verify that "SubscriptionFullfillmentModule" fulfills the subscription product line successfully
`Verify that the subscription product line gets fulfilled successfully.`

2020-10-26 08:36 UTC, zubair-arbi commented on ecommerce/subscriptions/tests/test_modules.py
> +            SubscriptionFulfillmentModule()._post_to_user_subscription_api(data=self.user_subscription_api_payload, user=self.user)
We can update this test like:

```python
with self.assertRaises(ConnectionError):
    # pylint: disable=protected-access
    SubscriptionFulfillmentModule()._post_to_user_subscription_api(
        data=self.user_subscription_api_payload, 
        user=self.user
    )
```

2020-10-26 08:56 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +        'number_of_courses': FuzzyInteger(1, 10).fuzz(),
@zubair-arbi I think this would be a quite long variable name. what about `subscription_course_limit` ? Also, should I do it in this PR or create another one as this would have to be refactored everywhere in the API, serializer and other places including from django admin of dev and local setups.

2020-10-26 08:57 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +def MockUserSubscriptionFactory():
done

2020-10-26 08:57 UTC, rehan99000 commented on ecommerce/subscriptions/tests/test_modules.py
> +    Unit tests for "SubscriptionModule".
done

2020-10-26 08:57 UTC, rehan99000 commented on ecommerce/subscriptions/tests/test_modules.py
> +        Verify that "SubscriptionFullfillmentModule" fulfills the subscription product line successfully
done

2020-10-26 08:57 UTC, rehan99000 commented on ecommerce/subscriptions/tests/test_modules.py
> +            SubscriptionFulfillmentModule()._post_to_user_subscription_api(data=self.user_subscription_api_payload, user=self.user)
done

2020-10-26 08:58 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/tests/test_views.py
> +            'subscription_active_status': 'true',
@zubair-arbi this is used to determine if a subscription is active and available to buy or not. A false value would mean that this subscription should not be buyable anymore. This `Active` depends on this.
![image](https://user-images.githubusercontent.com/20854114/97152834-51816d00-1793-11eb-88a4-e38b0c4fc9f0.png)

2020-10-26 09:38 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/tests/test_views.py
> +            'subscription_active_status': 'true',
Got it.

2020-10-26 09:46 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +        'number_of_courses': FuzzyInteger(1, 10).fuzz(),
I think we should stick with `subscription_number_of_courses` as initially decided in architecture diagram.
<img width="822" alt="Screen Shot 2020-10-26 at 2 44 34 PM" src="https://user-images.githubusercontent.com/5072991/97157449-eb4c1880-1799-11eb-8970-2b236968efdb.png">

2020-10-26 09:48 UTC, zubair-arbi commented on ecommerce/subscriptions/tests/test_modules.py
> +        self.assertEqual(connection_error.exception.request.headers.get('x-edx-ga-client-id'), self.user.tracking_context['ga_client_id'])
@rehan99000 I think we can remove these analytics headers assert statements. Also update the update code comment.

2020-10-26 10:09 UTC, rehan99000 commented on ecommerce/subscriptions/tests/test_modules.py
> +        self.assertEqual(connection_error.exception.request.headers.get('x-edx-ga-client-id'), self.user.tracking_context['ga_client_id'])
removed

2020-10-27 07:01 UTC, zubair-arbi commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +        'number_of_courses': FuzzyInteger(1, 10).fuzz(),
@ziafazal please suggest which name is better `subscription_number_of_courses` or `subscription_course_limit` ?

2020-10-27 07:11 UTC, ziafazal approved these changes
@rehan99000 overall looks good. Few minor things if you can look into them it would be great.

2020-10-27 07:11 UTC, ziafazal commented on ecommerce/subscriptions/api/v2/tests/test_serializers.py
> +        'limited-access',
could be moved into constants.

2020-10-27 07:11 UTC, ziafazal commented on ecommerce/subscriptions/api/v2/tests/test_serializers.py
> +            'limited-access': lambda subscription: {
could be moved into constants.

2020-10-27 07:11 UTC, ziafazal commented on ecommerce/subscriptions/tests/test_utils.py
> +        limited_subscription = self.create_subscription(product_attributes__subscription_type='limited-access')
`limited-access` could be moved to constants

2020-10-27 08:08 UTC, rehan99000 commented on ecommerce/subscriptions/tests/test_utils.py
> +        limited_subscription = self.create_subscription(product_attributes__subscription_type='limited-access')
moved

2020-10-27 08:08 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/tests/test_serializers.py
> +            'limited-access': lambda subscription: {
moved

2020-10-27 08:08 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/tests/test_serializers.py
> +        'limited-access',
moved

2020-10-27 08:09 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +def MockUserSubscriptionFactory():
done

2020-10-27 09:35 UTC, ziafazal commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +        'number_of_courses': FuzzyInteger(1, 10).fuzz(),
@zubair-arbi `subscription_number_of_courses` seems appropriate.

2020-10-29 07:13 UTC, rehan99000 commented on ecommerce/subscriptions/api/v2/tests/factories.py
> +        'number_of_courses': FuzzyInteger(1, 10).fuzz(),
As this change is unrelated to this PR, I will update this in a new PR under the same ticket.

2020-10-29 07:20 UTC, zubair-arbi approved these changes
LGTM 👍 

Merge these changes and address attribute name change `subscription_number_of_courses` in separate PR.

2020-10-29 07:28 UTC, merged