Create Payments site creation API
edly-io/ecommerce pull request #77
Opened 2021-04-27 13:30 UTC by rehan99000

**Description:**
This PR adds site creation API for payments.

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-2835

2021-04-28 08:59 UTC, iam-mhaseeb approved these changes
Overall LGTM 👍

2021-04-28 09:10 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/api/v1/views.py
> +            partner=payments_partner
The values being set here are the required fields for the ecommerce site configuration.

2021-04-28 10:39 UTC, burhandodhy approved these changes

2021-04-28 11:27 UTC, zubair-arbi requested changes
I have added my feedback.

2021-04-28 11:27 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +        'SESSION_COOKIE_DOMAIN': session_cookie_domain,
@iam-mhaseeb @rehan99000 do we need to set `SESSION_COOKIE_DOMAIN` here and also override it in `DJANGO_SETTINGS_OVERRIDE` ?

2021-04-28 11:27 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +            'COLORS': colors,
Why are we overriding colors here?

2021-04-28 11:27 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    return {
Lets order the keys in following order for readability:
```python
{
    'SESSION_COOKIE_DOMAIN': session_cookie_domain,
    'COLORS': colors,
    'FONTS': request_data.get('fonts', {}),
    'BRANDING': request_data.get('branding', {}),
    'DJANGO_SETTINGS_OVERRIDE': {
        'SESSION_COOKIE_DOMAIN': session_cookie_domain,
        'PLATFORM_NAME': request_data.get('platform_name', ''),
        'OSCAR_FROM_EMAIL': request_data.get('oscar_from_email', ''),
        'LANGUAGE_CODE': request_data.get('language_code', 'en'),
        'GTM_ID': request_data.get('gtm_id', ''),'PAYMENT_PROCESSOR_CONFIG': request_data.get('payment_processor_config', {}),
        'COLORS': colors,
        'EDLY_COPYRIGHT_TEXT': DEFAULT_EDLY_COPYRIGHT_TEXT,
        'CONTACT_MAILING_ADDRESS': request_data.get('contact_mailing_address', ''),
        'DISABLE_PAID_COURSE_MODES': request_data.get('disable_course_modes', False),
        'PANEL_NOTIFICATIONS_BASE_URL': request_data.get('panel_notification_base_url', ''),
        'SERVICES_NOTIFICATIONS_COOKIE_EXPIRY': DEFAULT_SERVICES_NOTIFICATIONS_COOKIE_EXPIRY,
        'EDLY_WORDPRESS_URL': '{protocol}://{marketing_url_domain}'.format(
            protocol=protocol,
            marketing_url_domain=wordpress_site,
        ),
        'FRONTEND_LOGOUT_URL': '{protocol}://{lms_root_domain}/logout'.format(
            protocol=protocol,
            lms_root_domain=lms_site,
        ),
    }
}
```

2021-04-28 11:27 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    Arguments:
nit: Add a newline before `Arguments` and `Returns`: https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#docstrings

2021-04-28 11:56 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +        'SESSION_COOKIE_DOMAIN': session_cookie_domain,
This is how it is in both onboarding documents.

2021-04-28 11:57 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    Arguments:
added

2021-04-28 12:01 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    return {
done.is there any convention to this?

2021-04-28 12:01 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +            'COLORS': colors,
This is how it is done in onboarding document

2021-04-28 12:15 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    return {
Some what. Keep the required fields for main site at top, keep similar keys togather

2021-04-28 12:15 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    Returns:
nit: add a new line above `requirements`

2021-04-28 12:16 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    """
Either remove `"""` or add docstring

2021-04-29 05:59 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    """
docstring added

2021-04-29 05:59 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +    Returns:
added

2021-04-29 11:55 UTC, asadmanzoor93 requested changes

2021-04-29 11:55 UTC, asadmanzoor93 commented on ecommerce/extensions/edly_ecommerce_app/constants.py
> +EDLY_INSIGHTS_GROUP = 'Edly Insights Admin'
@rehan99000 kindly remove these groups constants, since we have updated our permission to EDLY PANEL WORKER related only

2021-04-29 12:07 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/constants.py
> +EDLY_INSIGHTS_GROUP = 'Edly Insights Admin'
done

2021-04-30 06:59 UTC, zubair-arbi approved these changes
Changes looks good 👍

2021-04-30 09:20 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/permissions.py
> +class CanAccessSiteCreation(BasePermission):
```python
class CanAccessSiteCreation(BasePermission):
    """
    Checks if a user has the access to create and update methods for sites.
    """

    def has_permission(self, request, view):
         
        """
        Checks for user's permission for current site.
        """
        return request.user.is_staff and request.user.username == EDLY_PANEL_WORKER_USER
```

CC: @rehan99000 @burhandodhy @iam-mhaseeb @asadmanzoor93

2021-04-30 09:41 UTC, zubair-arbi approved these changes
LGTM 👍

2021-05-07 05:17 UTC, merged