[WIP] Integrate Cowpay payment gateway
edly-io/ecommerce pull request #89
Opened 2021-07-19 12:48 UTC by iam-mhaseeb

2021-09-24 06:22 UTC, zubair-arbi requested changes
I have added my feedback.

2021-09-24 06:22 UTC, zubair-arbi commented on ecommerce/templates/payment/cowpay.html
> +{# NOTE: Using compress tags here results in the JS not being loaded. #}
Do we need this comment?

2021-09-24 06:22 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/models.py
> +class CowpayPaymentRecord(models.Model):
I believe this model should be in https://github.com/edly-io/ecommerce/blob/develop-juniper/ecommerce/extensions/payment/models.py

Since we are doing a generic integration not for just edly.

2021-09-24 06:22 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/forms.py
> +class CowpayFawryPaymentForm(forms.Form):
I believe this model should be in https://github.com/edly-io/ecommerce/blob/develop-juniper/ecommerce/extensions/payment/forms.py

Since we are doing a generic integration not for just edly.

2021-09-24 06:37 UTC, zubair-arbi commented on ecommerce/extensions/edly_ecommerce_app/models.py
> +class CowpayPaymentRecord(models.Model):
Also use timestamped model

2021-09-24 06:58 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/forms.py
> +def update_basket_queryset_filter(form, user):
moved this code to payment forms

2021-09-24 06:58 UTC, rehan99000 commented on ecommerce/templates/payment/cowpay.html
> +{# NOTE: Using compress tags here results in the JS not being loaded. #}
removed it

2021-09-24 06:59 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/models.py
> +class CowpayPaymentRecord(models.Model):
Moved the code to payment models

2021-09-24 06:59 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/forms.py
> +class CowpayFawryPaymentForm(forms.Form):
moved this form to payment forms

2021-09-24 07:02 UTC, asadmanzoor93 requested changes

2021-09-24 07:02 UTC, asadmanzoor93 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +            merchant_reference_id = "{}{}".format(basket.order_number, int(datetime.now().timestamp()))
Nit: Please try to follow a consistent python-string-format method. Here you are using `empty placeholders` and later on you are using `named indexes` for signature

2021-09-24 13:23 UTC, zubair-arbi approved these changes
A few nits, otherwise changes looks good.

Please squash to one verbose commit after addressing all the feedback.

2021-09-24 13:23 UTC, zubair-arbi commented on ecommerce/extensions/payment/processors/cowpay.py
> +        Raises:
nit: add a new line before `Raises` section

2021-09-24 13:23 UTC, zubair-arbi commented on ecommerce/extensions/payment/views/cowpay.py
> +        receipt_url = "{}?{}".format(receipt_url, urlencode(params))
nit: use single quote in code and double quotes in comments/descriptions.

2021-09-27 07:03 UTC, ziafazal requested changes
@rehan99000 completed first round of review.

2021-09-27 07:03 UTC, ziafazal commented on ecommerce/static/sass/partials/views/_basket.scss
> +                background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAA0CAYAAAA62j4JAAAcHklEQVRogbV6aZBkV3Xmd5e35b5UZmUt3V29d6u7hSQktAECYQRGwkYMsjHjgRjWCY0gZJADYuwZm/E2CsYE9jBjw4
why you are using encoded bytes of image instead of url?

2021-09-27 08:11 UTC, rehan99000 commented on build.js
> +            name: 'js/apps/cowpay_receipt_app',
Its not a complete app. This is kind of an entry point to a page in backbonejs. As u can see just above it, order receipt page works the same way.

2021-09-27 08:13 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/api/v1/constants.py
> +COWPAY_WAFFLE_SWITCH = 'cowpay_enabled'
In the beginning, I was implementing this considering it an Edly only feature so thought to put it behind a waffle switch. but since we are proceeding with it as a general feature, I am removing it.

2021-09-27 08:27 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/api/v1/constants.py
> +COWPAY_NAME = 'cowpay'
removed the constant

2021-09-27 08:27 UTC, rehan99000 commented on ecommerce/extensions/payment/processors/cowpay.py
> +        card_type = COWPAY_NAME
done

2021-09-27 08:27 UTC, rehan99000 commented on ecommerce/extensions/payment/forms.py
> +class CowpayFawryPaymentForm(forms.Form):
`PaymentForm` has a lot of extra fields like address lines, country etc that we don't need. Stripe form is inherited the same way as well.

2021-09-27 08:28 UTC, rehan99000 commented on ecommerce/extensions/payment/views/cowpay.py
> +        receipt_url = reverse('cowpay:receipt')
updated.

2021-09-27 08:34 UTC, rehan99000 commented on ecommerce/extensions/payment/models.py
> +    payment_gateway_reference_id = models.CharField(max_length=512)
This is cowpay payment record not fawry record. The `payment_gateway_reference_id` only comes in the response for cowpay fawry payment request. Since we are creating this record for all cowpay payments whether fawry or credit card, keeping this as primary key would not work. However, for credit card payments, we receive a `cowpay_payment_id` which I am setting as `merchant_reference_id`. So, maybe we can make the `merchent_reference_id` as primary key.

2021-09-27 08:35 UTC, rehan99000 commented on ecommerce/static/sass/partials/views/_basket.scss
> +                background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAA0CAYAAAA62j4JAAAcHklEQVRogbV6aZBkV3Xmd5e35b5UZmUt3V29d6u7hSQktAECYQRGwkYMsjHjgRjWCY0gZJADYuwZm/E2CsYE9jBjw4
This was done by haseeb as initial work. This will be replaced with proper image once I get it from @mamjad00

2021-09-27 08:40 UTC, rehan99000 commented on ecommerce/extensions/payment/processors/cowpay.py
> +        self.record_processor_response(CowpayPaymentRecordSerializer(payment_record).data, transaction_id=merchant_id, basket=basket)
we could save the processor response. In that case, it would be just `response` not `response.data`. Updated the code

2021-09-28 11:26 UTC, rehan99000 commented on ecommerce/extensions/payment/models.py
> +    payment_gateway_reference_id = models.CharField(max_length=512)
Updated the field

2021-09-28 11:26 UTC, rehan99000 commented on ecommerce/extensions/payment/processors/cowpay.py
> +        )
Done

2021-09-28 11:27 UTC, rehan99000 commented on ecommerce/extensions/basket/views.py
> +                context.update(get_cowpay_data(payment_processors, self.request))
refactored code for this

2021-09-28 11:27 UTC, rehan99000 commented on ecommerce/extensions/payment/models.py
> +    payment_gateway_reference_id = models.CharField(max_length=512)
done

2021-09-28 11:28 UTC, rehan99000 commented on ecommerce/extensions/payment/views/cowpay.py
> +        receipt_url = "{}?{}".format(receipt_url, urlencode(params))
done

2021-09-28 11:28 UTC, rehan99000 commented on ecommerce/extensions/payment/processors/cowpay.py
> +        Raises:
added

2021-09-28 11:29 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +                'Authorization': 'Bearer {token}'.format(token=cowpay_processor.get('token')),
handled exception here

2021-09-28 11:29 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
> +            merchant_reference_id = "{}{}".format(basket.order_number, int(datetime.now().timestamp()))
updated

2021-09-28 11:30 UTC, rehan99000 commented on ecommerce/static/js/payment_processors/cowpay.js
> +            var $paymentForm = $('#paymentForm'),
done

2021-09-28 11:31 UTC, rehan99000 commented on ecommerce/static/js/payment_processors/cowpay.js
> +                console.log(e);
this log is left because the browser callback listener here is still a bit erratic. This is to confirm desired behavior.

2021-09-28 11:35 UTC, rehan99000 commented on ecommerce/static/js/payment_processors/cowpay.js
> +                    }).then(response => response.json())
done

2021-09-29 09:21 UTC, asadmanzoor93 approved these changes
LGTM 👍 Kindly squash your commits before merging.

2021-09-29 13:43 UTC, ziafazal approved these changes
👍

2021-09-29 13:46 UTC, zubair-arbi commented on ecommerce/templates/payment/cowpay.html
> +<script src="https://staging.cowpay.me/js/plugins/CCIframePlugin.js"></script>
Should we change this URL `https://staging.cowpay.me/js/plugins/CCIframePlugin.js` for prod?

2021-09-29 14:45 UTC, rehan99000 commented on ecommerce/templates/payment/cowpay.html
> +<script src="https://staging.cowpay.me/js/plugins/CCIframePlugin.js"></script>
Yes we would need to remove the staging. Let me update it.

2021-09-30 08:38 UTC, merged