Updates middlware and site course validators to use multiple edx-orgs
edly-io/ecommerce pull request #91
Opened 2021-08-10 06:31 UTC by rehan99000

2021-08-12 09:46 UTC, asadmanzoor93 requested changes
Add/update related unit tests.

2021-08-12 11:24 UTC, rehan99000 commented
> Add/update related unit tests.

The change does not affect any tests and is just to adjust the changes in https://github.com/edly-io/edx-platform/pull/253

2021-08-12 11:54 UTC, taimoor-ahmed-1 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
>      Returns "edx-org" value from the "edly-user-info" cookie.
"edx-org" -> "edx-orgs"

2021-08-12 11:57 UTC, rehan99000 commented on ecommerce/extensions/edly_ecommerce_app/helpers.py
>      Returns "edx-org" value from the "edly-user-info" cookie.
fixed

2021-08-12 11:58 UTC, taimoor-ahmed-1 approved these changes
👍

2021-08-13 04:55 UTC, asadmanzoor93 approved these changes

2021-08-13 05:29 UTC, merged