Update subscriptions serializers with site's default currency and currency code
edly-io/ecommerce pull request #97
Opened 2021-09-10 13:05 UTC by asadmanzoor93

**Description:**  This PR updates subscriptions serializers with the site's default currency and currency code.

**JIRA:** 
https://edlyio.atlassian.net/browse/EDLY-3640
https://edlyio.atlassian.net/browse/EDLY-3616

**Merge checklist:**

- [ ] All reviewers approved
- [ ] Commits are (reasonably) squashed

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

**Note:** Please add screenshots for any viewable change.

2021-09-10 13:21 UTC, burhandodhy requested changes
Kindly update tests.

2021-09-13 06:02 UTC, burhandodhy approved these changes
LGTM

2021-09-15 08:34 UTC, taimoor-ahmed-1 commented on ecommerce/subscriptions/api/v2/tests/test_serializers.py
>  from ecommerce.subscriptions.api.v2.serializers import (
add empty line

2021-09-16 12:07 UTC, burhandodhy commented on ecommerce/subscriptions/api/v2/tests/test_serializers.py
>  from ecommerce.subscriptions.api.v2.serializers import (
Done

2021-09-16 12:09 UTC, taimoor-ahmed-1 approved these changes
👍

2021-09-20 05:39 UTC, merged